### PR TITLE
Add Microsoft Azure configuration section

### PR DESCRIPTION
**Pull request by mschnitzer**

### CODE REVIEW

**Comment by eduardoj** [comment]
Rebased. @openSUSE/open-build-service please review.

**Comment by ChrisBr** [comment]
Nobody reviewed I guess :thinking:

**Comment by Ana06** [comment]
can we merge it now? :thinking:

**Comment by ChrisBr** [comment]
> can we merge it now? thinking

You approve it, you merge it, right? :smile:

**Pull request merged**
