### PR TITLE
F/movetoadmguide

### PR DESCRIPTION
**Pull request by ghost**
@[](url)

### CODE REVIEW

**Comment by adrianschroeter** [comment]
hey, I largely agree with your changes, just

* Dropping Stefan Knorr as author is not so nice
* A generic highlevel OBS server architecture should remain in reference guide, since it is important to know  for understand the interface and work job concepts at least.
* Could you maybe squash your commits a bit? for example the "delete me"?

**Comment by hennevogel** [comment]
@sknorr are you going to work on this?

**Comment by sknorr** [comment]
Yes, I still have it on the list. But not for today.

**Comment by sknorr** [comment]
This is hopelessly bitrotted at this point, so it does not make sense to try to rebase anymore. I have however tried to take at least a few things from this PR.

**Pull request closed without merging**
