### PR TITLE
Remove all empty documentation sections

### PR DESCRIPTION
**Pull request by okurz**
They are just confusing and disappointing users and provide a false impression.

Less is more :-)

### CODE REVIEW

**Comment by okurz** [comment]
Fixing https://github.com/openSUSE/obs-docu/issues/3

**Comment by hennevogel** [comment]
So hiding titles of non existing topics helps people looking for documentation on those topics how?

**Comment by okurz** [comment]
* saves time not wasted on looking for an empty section
* less dissappointment -> * less grumpy comments by people on IRC that the documentation is incomplete

**Comment by hennevogel** [comment]
People are rightfully grumpy. And nothing will be better for them if we remove the empty sections, so I they will still complain. I don't follow your argument, sorry

**Comment by okurz** [comment]
Complaining about "documentation could be better" is one thing - of course it can always be better. But having empty sections for so many years is just misleading. People get their hopes up and then are disappointed. Why not keep it simple and the documentation mentions everything that is covered and that's it. If I would understand more about OBS I would maybe contribute to it but probably not even to the empty sections because I don't know what the original author had as intentions. I think every other potential contributor would feel the same. Keeping sections with "to be implemented…" is like the webpages from the 1990s when so many people wanted to jump the train - "I can have my own webpage, yay!" - but did not know what to put there so you are greeted with these animated construction site gif's which made your eyes bleed and you never take a look again on that page - https://motherboard.vice.com/en_us/article/this-guy-compiled-every-under-construction-gif-from-the-90s

Did I do anything wrong from technical perspective, e.g. regarding the syntax? Did I delete wrong tags or should I delete more to make it complete?

**Pull request closed without merging**
