### PR TITLE
Fast forward docbook stylesheets 10 years

### LINKED ISSUE #226: Remove/replace Google+ in the "Share this page" Documentation footer
The footer of the OBS User Guide contains a "Share this page" feature that still provides to share the page via Google Plus, which has been discontinued in April 2019. I'd like to suggest removing that part, or replace it with alternative social networks (e.g. Pinterest, Instagram, etc.)

Screenshot from 2022-03-23 10-49-37

### PR DESCRIPTION
**Pull request by hennevogel**
Fixes #226

### CODE REVIEW

**Review by tomschr — APPROVED** [review]
Looks fine! :+1: :slightly_smiling_face:

**Comment by hennevogel** [comment]
Or not https://github.com/openSUSE/obs-docu/runs/5694508473?check_suite_focus=true

**Comment by hennevogel** [comment]
@tomschr where is that supposed to come from?

**Comment by tomschr** [comment]
@tomschr I suppose your container does not contain the latest stylesheet update. Unfortunately, I cannot see the version of the stylesheet package used inside the container. Maybe add an additional debug output of all relevant RPM package in your GitHub Action?

I would recommend to add the latest stylesheet package from [Documentation:Tools/suse-xsl-stylesheets](https://build.opensuse.org/package/show/Documentation:Tools/suse-xsl-stylesheets). The current version is 2.83.

**Pull request merged**
