### PR TITLE
Document placeholder variables for SCM/CI Integration

### PR DESCRIPTION
**Pull request by dmarcoux**
To test this locally:
1. Pull the changes from this PR, then run `daps2docker .`
2. Open the generated user guide in your favorite browser: `firefox /tmp/daps2docker-SXo2tVAc/obs-user-guide/html/book.obs-user/cha.obs.scm_ci_workflow_integration.html` (the string after `daps2-docker-` will be different).

Preview of the changes:
documentation

**DO NOT MERGE**: Wait for https://github.com/openSUSE/open-build-service/pull/13498 to be merged and deployed.

### CODE REVIEW

**Comment by tomschr** [comment]
Thanks for your contribution. :+1: 

Just one friendly remark regarding this pull requests. I know it's tempting to add TODOs as reminder. However, I would recommend NOT to add them. This gives us a bad reputation and let our readers think the documentation is just "draft". TODOs are for the writer, not for the reader.

However, if you really want to leave some notes in your document which shouldn't be visible to our readers you have two options:

* Use a XML comment (`<!-- ... -->`) and add your notes there. This is possible everywhere.
* Use the `<remark>...</remark>` element. This is only visible if the document is rendered in draft mode. However, this is only possible inside block elements or inside division elements (for example, after `<section><title>`.

Thank you! :slightly_smiling_face:

**Comment by dmarcoux** [comment]
This PR is a draft and I'm not going to keep the TODOs in the PR whenever I mark it as "ready for review" :slightly_smiling_face:

**Comment by krauselukas** [comment]
PR is ready for review now, since the functionality is merged and deployed on the OBS side

**Review by krauselukas — APPROVED** [review]
LGTM

**Pull request merged**
