### PR TITLE
source services: clarify section on "buildtime mode"

### PR DESCRIPTION
**Pull request by mwilck**
Improve English and clarify network access restrictions in buildtime mode.

### CODE REVIEW

**Comment by adrianschroeter** [comment]
Thanks a lot, but please flag the build.opensuse.org specific part with os="opensuse" as described in the howto of these books.

**Comment by mwilck** [comment]
@adrianschroeter Like this, maybe?

**Comment by bgeuken** [comment]
Thanks a lot for your contribution 💐

**Comment by adrianschroeter** [comment]
yep, great :)

**Pull request merged**
